// <auto-generated />
using System;
using ExamenDSE.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenDSE.Migrations
{
    [DbContext(typeof(ProductosDBContext))]
    partial class ProductosDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamenDSE.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "---",
                            Nombre = "Electrónica"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "---",
                            Nombre = "Ropa"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "---",
                            Nombre = "Alimentos"
                        });
                });

            modelBuilder.Entity("ExamenDSE.Models.Productos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "Smartphone Samsung S24 Ultra",
                            Nombre = "Smartphone",
                            Precio = 299.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Descripcion = "Camiseta Nike",
                            Nombre = "Camisa",
                            Precio = 19.99m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            Descripcion = "Pan Bimbo",
                            Nombre = "Pan",
                            Precio = 1.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Descripcion = "Laptop Dell",
                            Nombre = "Laptop",
                            Precio = 799.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 2,
                            Descripcion = "Zapatos Adidas",
                            Nombre = "Zapatos",
                            Precio = 49.99m,
                            Stock = 150
                        });
                });

            modelBuilder.Entity("ExamenDSE.Models.Productos", b =>
                {
                    b.HasOne("ExamenDSE.Models.Categoria", "categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("ExamenDSE.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
